#! /bin/zsh

init_dir=$(pwd)
file_dir=$(
    cd "$(dirname "$0")"
    pwd
)
cd $file_dir
cd ./app

docker build -t notion-blog-frontend . --no-cache
docker tag notion-blog-frontend:latest asia-northeast1-docker.pkg.dev/dajare-evaluate/hassaku-travel-blog/frontend:latest
docker push asia-northeast1-docker.pkg.dev/dajare-evaluate/hassaku-travel-blog/frontend:latest

cd $init_dir
