#! /bin/zsh

init_dir=$(pwd)
file_dir=$(
    cd "$(dirname "$0")"
    pwd
)
cd $file_dir
cd ./backend

docker build -t notion-blog-backend .
docker tag notion-blog-backend:latest 705654573183.dkr.ecr.ap-northeast-1.amazonaws.com/notion-blog-backend:latest
docker push 705654573183.dkr.ecr.ap-northeast-1.amazonaws.com/notion-blog-backend:latest

cd $init_dir
