#! /bin/zsh

init_dir=$(pwd)
file_dir=$(
    cd "$(dirname "$0")"
    pwd
)
cd $file_dir
cd ./app

docker build -t notion-blog-frontend .
docker tag notion-blog-frontend:latest 705654573183.dkr.ecr.ap-northeast-1.amazonaws.com/notion-blog-frontend:latest
docker push 705654573183.dkr.ecr.ap-northeast-1.amazonaws.com/notion-blog-frontend:latest

cd $init_dir
