version: "3"
services:
    backend:
        build:
          context: ./backend
        volumes:
            - ./backend/.dockervenv:/src/.venv
            - ./backend:/app
        ports:
            - 8000:8000
